### ISSUE TITLE
where to add apply security patch in script?

### ISSUE THREAD

**Issue by muranava** [picomatic/builde#1]
Hi
if i wanted to add commands to include a security patch where would i place it in your script?
thx

**Comment by picomatic** [comment]
You can use userscripts in /srv/userscripts, for exapmple "pre-build.sh" there you can do the patches just before buiding, see here: https://gitlab.e.foundation/e/os/docker-lineage-cicd/-/blob/master/src/build.sh

**Comment by muranava** [comment]
ok thanks!

**Comment by picomatic** [comment]
No not needed. just put script in /srv/userscripts
